### ISSUE TITLE
Resources for beginners where that can learn more about basic economy.

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/handbook-of-money#3]
Add a list of resources good for beginners. Like [Crash Course](https://www.youtube.com/watch?v=3ez10ADR_gM&list=PL1oDmcs0xTD-dJN1PL2N1urX0EKupBJCQ).

**Comment by HardeepAsrani** [comment]
Always love any course by Green brothers.

**Comment by mileamadalin** [comment]
Tey are? https://www.youtube.com/c/vlogbrothers

**Comment by mileamadalin** [comment]
I also found that one https://greenbrothers.ch/en/products/ :))

**Comment by HardeepAsrani** [comment]
@mileamadalin Yea, that channel is run by Vlogbrothers.
